name: Node CI
on: [push, pull_request]
jobs:
  node:
    name: "${{ matrix.kind }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup Node"
        uses: "actions/setup-node@v2"
        with:
          node-version: "14"

      - name: "Setup Deno"
        uses: "denoland/setup-deno@v1"
        with:
          deno-version: "v1"
      
      - name: "Version"
        if: "github.ref == 'refs/heads/main'"
        id: "version"
        env:
          MSG: "${{ github.event.head_commit.message }}"
        run: |
          echo "VERSION=$(deno run -Aq https://crux.land/38Jyby)" >> $GITHUB_ENV
          echo "${{ env.VERSION }}"
      - name: "Print Version"
        if: "github.ref == 'refs/heads/main'"
        run: "echo ${{ env.VERSION }}"
          
      
